<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Edlink</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <WarningLevel>4</WarningLevel>
    <ApplicationIcon>ed.ico</ApplicationIcon>
    <AssemblyTitle>edlink</AssemblyTitle>
    <Product>edlink</Product>
    <Copyright>Copyright ©  2026</Copyright>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="cat.ico" />
    <Content Include="ed.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.28" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
</Project>